ease-crc/soma

- scripts/ecv.sh
- scripts/elan_cv.py
The two files are the python script to crawl the EASE taxonomy, and a bash script to call it with the parameters properly set up so that the elan branch of the ontology can replicate Celeste's current vocabulary.
> Controlled vocabulary generation scripts.

- owl/EASE-OBJ.owl
> adjusted description of *DesignedBlade*

- owl/EASE-ACT.owl
a region with labels identifying the state of execution
> Execution state

- owl/EASE-ACT.owl
- owl/EASE-OBJ.owl
- owl/EASE.owl
Fixed issue with *contains* only being defined for events, now there is a general contains and more specific *containsEvent* and *containsObject* (in EASE-OBJ).
> contains relation

- owl/EASE-PROC.owl
First attempt on a *Contact* taxonomy. **This might need some further discussion**
sorry for including definition of properties *interactsWith*, *supports* and *supportedBy* here. I could remove them again for this request.
> Contact taxonomy

- .github/actions/hermit/Adding-assembly-target.patch
- .github/actions/hermit/Dockerfile
- .github/workflows/ontology.yml
- scripts/hermit_test.py
This PR builds HermiT from https://github.com/owlcs/hermit-reasoner.git and runs it on the EASE-UGLY.owl. 
The result is then processed and concerning subsumptions (equal or inheritance to owl#Nothing, equal or inheritance to owl#bottomObjectProperty) are reported.
An example output (assuming #59 is applied):
```
* - http://www.ease-crc.org/ont/EASE-ACT.owl#Planning
- http://www.ease-crc.org/ont/EASE-ACT.owl#Taxis
- http://www.ease-crc.org/ont/EASE-PROC.owl#ArtifactContact
- http://www.ease-crc.org/ont/EASE-PROC.owl#Boiling
- http://www.ease-crc.org/ont/EASE-PROC.owl#Collision
- http://www.ease-crc.org/ont/EASE-PROC.owl#Contact
- http://www.ease-crc.org/ont/EASE-PROC.owl#Deformation
- http://www.ease-crc.org/ont/EASE-PROC.owl#Fixation
- http://www.ease-crc.org/ont/EASE-PROC.owl#FluidFlow …
```
> Adding HermiT reasoner to workflow.

- owl/EASE-STATE.owl
- owl/EASE.owl
The pull request does some refactoring
- move State definition to EASE-STATE.owl
- rename Gestallt to StateType
And it changes the comment of the *State* concept. Note that the previous comment was rather describing what a configuration is, so I have moved it to the *Configuration* concept.
> States refactoring

- owl/EASE-PROC.owl
This pull requests deletes the concept *ForceEvent* and introduces a new notion *ForceInteraction* instead. *ForceInteractions* are process types with at least two roles: the agonist and the antagonist. The agonist has a tendency to either preserve or alter some physics aspect. An example is "opening the door" where the agent (agonist) needs to overcome the force that keeps the door closed.
I also had to re-arrange concepts defined as sub-class of *ForceEvent* before,
and I deleted the *Contact* sub-branch because contact is a state rather then a process.
> Forceinteraction

- prolog/uglify.pl
convert any 'http://www.ease-crc.org/SOMA[.*].owl#[.*]' IRI to 'http://www.ease-crc.org/SOMA.owl#[.*]' in the uglify step
> uglify all SOMA iri's

- owl/SOMA-ACT.owl
- owl/SOMA-ELAN.owl
> Added cutting, slicing, dicing.

- .github/workflows/ontology.yml
- prolog/uglify.pl
extends CI to auto-deploy on release
> deploy tagged releases

- docs/NEEM-specification/content/representation/neem-narrative/neem-narrative.tex
Hi,
This is first version for some of taxonomies.
Please check it out and let me know if you think it needs to be changed.
I will create appendix section later. 
Best,
Abhijit
> Document soma

- .gitignore
> Adding SOMA.owl to gitignore.

- owl/SOMA-OBJ.owl
- added missing inverse of `hasMassAttribute`
- added `NetForce` concept, `hasNetForce` and `hasForceValue` properties
> Mass and NetForce attributes

- owl/SOMA-OBJ.owl
This pull requests adds a few new concepts and properties to model kinematics.
- joints are physical bodies with child and parent link
- there are different types of joints
- each joint has a joint state attribute
- some joints may have physical limits
- components of objects may be root or leaf of the kinematic structure of the object
> added URDF-like model for joints

- owl/SOMA-OBJ.owl
03f5da3 had multiple missing end-tags in SOMA-OBJ. This PR adds those back.
> Adding missing end-tags.

- prolog/uglify.pl
> Correcting namespace, re-adding /ont/ into the path.

- owl/SOMA-ACT.owl
Partially addresses #158 and what's left out (GetX tasks, where X is a parameter) will be defined in cram_knowledge.
> A few more tasks added to match CRAM's repertoire

- docs/NEEM-handbook/content/representation/neem-background.tex
- docs/NEEM-handbook/content/representation/neem-narrative/neem-narrative.tex
- docs/NEEM-handbook/main.tex
Removed one todo that showed up in the pdf. Also fixed the header so that it now is "Beetz et. al." and not "Authors Suppressed Due to Excessive Length".
> Minor fixes: Removed todos, added author, fixed header

- .github/workflows/evaluation.yml
the definitions in SOMA-HOME are not yet checked by Hermit and OOPS.
> use SOMA-HOME for evaluation

- owl/SOMA-ACT.owl
- owl/SOMA-OBJ.owl
- owl/SOMA-PROC.owl
- owl/SOMA-SAY.owl
- owl/SOMA-STATE.owl
- owl/SOMA-WF.owl
- owl/SOMA.owl
NOTE: PR is not done yet. The purpose of opening it was to have a discussion board here to clarify some things (see next message).
Currently done: "most" of SOMA.owl, except for a few entities that need clarification.
> Added comments to some SOMA entities

- .github/workflows/evaluation.yml
> Pass DUL v32 and IOLite explicitly to hermit.

- owl/SOMA-ACT.owl
- owl/SOMA-OBJ.owl
(I will explain the cleanups, and a surprise in the diff, in the next comment.)
The approach I propose is the following: we have the Events to refer to things that actually happen. Events are the initial building bricks of our logs. We can add semantics (aka meaning aka interpretations) to Events via other types of concepts. In particular, we would now say that Events manifest Situations, which themselves satisfy some Descriptions from whatever theories, planning domain descriptions, etc. we have available.
The reason for this is that Situations don't have to manifest in Events, so we can speak of prevented Situations, or expected but not occurring Situations. As an example, we might have an Action A, which is the manifestation of some Situation S, and we expect this Action to result in a …
> Pre/postconditions, manifestations, preventions. And some cleanup.

- scripts/OntoMetrics.sh
Changed to new api of ontometrics and changed some header variables
> Changed to new api of OntoMetrics

- .github/workflows/deployment.yml
- owl/DUL.owl
- owl/SOMA-ACT.owl
- owl/SOMA-SAY.owl
- owl/SOMA-WF.owl
- owl/SOMA.owl
I added DUL and changed the deployment workflow, so that DUL should be accessible over our server.
For the moment I removed left over IOLite imports. We have to change references in some files.
> Moved DUL to a local server

- .gitignore
- owl/catalog-v001.xml
> Local setup for Protege Workenvironment

- owl/DUL.owl
The IRI of the repositories DUL did not match the hosted version.
> Fixed Local Duls IRI

- .github/workflows/deployment.yml
The neem handbook and the metrics should have also a versioned release with tags
> Added versioned release of files

- scripts/oops.py
This PR fixes https://github.com/ease-crc/soma/issues/253
That is is working again can be seen here in my CI log:
https://github.com/sasjonge/soma/actions/runs/2717669002
Here is how it looked before the fix:
https://github.com/ease-crc/soma/actions/runs/2717603479
> Fix for oops api call

- docs/vocab/SOMA-vocabulary.tex
This will fix https://github.com/ease-crc/soma/issues/267
I'm not sure why suddenly the URL became a problem, but I tested this on my master and it worked.
> Fix for Vocabulary Pythonlatex CI Job

- owl/SOMA-ACT.owl
- owl/SOMA-ALL.owl
- owl/SOMA-IO.owl
- owl/SOMA-SAY.owl
- owl/SOMA.owl
This PR introduces a number of new classes, properties and axioms to model the communication between agents.
It does not yet include qualities of communicated information, e.g., confidence in an answer, but only the general structure of a Communication Action and Communication Tasks with Messages, Senders, Receivers and Channels including a basic cause/reaction relationship between Actions (without any assumptions on perlocutionary effects / BDI).
> Model of Communication between Agents

- RELEASE_NOTES.md
These are the updated release notes for version 2.0.0 of SOMA.
> Release Notes for Version 2.0.0

- index.html
The keys for the resulting metric dict have changed.
> Fix metrics for new release on SOMA page

- owl/SOMA-HOME.owl
The new SOMA-HOME still imports things it shouldn't import, I fixed it by changing SOMA-HOME itself.
> Fix soma-home

- owl/SOMA-ACT.owl
Depends on [PR ](https://github.com/ease-crc/soma/pull/294)
> Added dispositions to the task

- owl/SOMA-ACT.owl
- owl/SOMA-AGENT.owl
- owl/SOMA-ALL.owl
- owl/SOMA-OBJ.owl
- owl/SOMA.owl
- owl/catalog-v001.xml
Introduced the pattern to model preferences.
#286 should be merged before this.
> SOMA-Agent

- RELEASE_NOTES.md
This is a draft for the updated release notes for 3.0.0
> Release Notes for Version 3.0.0
