ease-crc/soma

- owl/EASE.owl
Adds two fairly generic annotation properties, and for each of them a more specific subproperty related to a particular user group of the ontology.
"nickname": similar to 'label', but without GUI or reasoner impact in Protege; avoiding Protege problems is why this is not a label subproperty. Nicknames are used by particular software working with the ontology as a way to give community-specific names.
"ELANName": subproperty of nickname. If present, used by the controlled vocabulary generation script to create a vocabulary entry. By default, the concept name itself is used for the vocabulary entry.
"UsageGuideline": annotation of a concept with an indication of how it is to be used in some context.
"ELANUsageGuideline": provides a short description, similar to a definition, of a controlled …
> Added annotation properties for ELAN generation.

- owl/EASE-ACT.owl
One of the more painless merges between the ELAN branch and master, this defines thinkaloud related concepts that didn't have correspondents in master yet.
It also defines CommunicationTask and CommunicationTopic (which is a subclass of Role). There may be something related to CommunicationTask already in master, should see how these can be merged.
> Added think-aloud and communicationtask related concepts.

- owl/EASE-ACT.owl
Object creation, modification, and search.
Note that the modification tree can, and probably should, absorb some of the already existing tasks. In general, it seems to be a nicer taxonomy when there are fewer siblings underneath a superconcept, so that more information about the similarity between different concepts can be encoded.
Currently however, no other tasks except Transport were moved to subclasses of Modifying.
> Superclasses for object-related tasks.

- owl/EASE-ACT.owl
- owl/EASE-PROC.owl
The last and biggest patch to get the stuff from the ELAN branch to master.
The hierarchy underneath PhysicalTask is now less flat, as there are some intermediate level concepts such as PosturalMovement, Locomotion, ManipulationTask, and Actuating, which together absorb most of the tasks that were already present in master.
Not all tasks under master are absorbed, though arguably should be.
Some of the intermediate concepts seem very strongly related: Locomotion and Navigation; Actuating and ManipulationTask. I've tried to make clear in rdfs:comments what the differences between these are supposed to be. I think a difference does exist, but also significant gray areas.
An example is Holding. Historically, this was treated as an Actuating (which can be seen from the ELANName …
> Added body-related tasks.

- owl/EASE-OBJ.owl
The pull request refactors the *Support* disposition to avoid conflicts with state/process module. The idea is that the role of interest is *Deposit* which is used to put down the *DepositedObject*. The dispoition type I called *Deposition*. Please let me know in case you have a better idea.
Another reason for this is that I rather want to concentrate on the task aspect of dispositions, not so much on their relation to force interactions such that I think *support* should not be a disposition on its own, but it is rather a phase when executing certain tasks that are afforded by some disposition.
> +Deposit +DepositedObject +Deposition

- owl/EASE-OBJ.owl
- owl/EASE-STATE.owl
Refactoring of *AssemblyConnection* and *AssemblyConnectionConfiguration*.
- I would prefer to use *Linkage* over *Assembly* to match the disposition model
- I think *LinkageGestallt* should probably not be a sub-concept of *ContactGestallt*. Thinking on relations they imply (i.e. *isLinkedTo* and *isInContactWith*), I would not see *isLinkedTo* as a sub-property of *isInContactWith*.
- In addition, the pull request adds property *isLinkedTo* in EASE-OBJ
> Assembly -> Linkage refactoring

- .github/actions/convert/Dockerfile
- .github/workflows/neem_spec.yml
- .github/workflows/ontology.yml
- .gitignore
- README.md
- docs/NEEM-specification/Makefile
- prolog/uglify_ease.pl
- scripts/uglify_ease_as_owl.py
This commit uglifies the ontology without the need of ROS, converts it
to a proper owl file, and uploads the artifacts.
This commit also adds automatic building for the specification docs.
It updates the README to contain badges for both jobs.
Last, it adds an optional step which pushes the compiled ontologies onto
the gh-pages branch if a secrets.ACCESS_TOKEN is set and the build
happened on the master branch.
> Adding workflow to uglify and build the docs.

- prolog/uglify_ease.pl
This will cause EASE-UGLY to not have package imports any more.
> ignore all imports of EASE ontology modules in uglify script

- owl/EASE.owl
This PR sets all array_types to be equivalent to xsd:string. 
Resolves #57.
> Asserting array_* to be equivalent to xsd:string.

- owl/EASE-PROC.owl
This pull requests adds *hasProcessType* and its inverse *isProcessTypeOf*.
These properties are defined analogously to DUL's *isTaskOf* and *hasTask*.
They are used to state that a role is related to a process type.
I am not entirely happy with the naming but it is consistent with DUL.
Protege also added some missing forward declarations.
> +hasProcessType

- owl/EASE-PROC.owl
This pull request fixes some faulty *ProcessType* definitions using a new relation that is used to relate process types to roles.
Before they were axiomatized as if they were events, restricing their *participants*. But concepts may not have any participants.
depends on #61
> Proctype fix

- owl/EASE-STATE.owl
This pull requests defines missing relations to associate *Gestallts* with *Roles* (similar to *hasTask* and *isTaskOf*).
Furthermore, I started using these relations for all *Gestallt* concepts. However, this makes the specific *Configuration* definitions obsolete (as they were only defining the roles). Hence, I removed them. Only the toplevel *Configuration* class remains as it was.
An argument for doing this is to keep it consistent with how we handle other types of events.
Another is that Configuration and Gestallt branches had redundant structure which makes modelling a bit more cumbersome (as you potentially need to do changes in two places)
> +isGestalltOf -specific configuration concepts

- owl/EASE-OBJ.owl
This pull request only renames the *Alteration* disposition concept to *Variability* to avoid name clash with EASE-PROC.
I think *Alteration* should rather be defined as *ProcessType*.
> rename Alteration disposition to Variability

- owl/EASE-ACT.owl
- fixed faulty definition of Planning and Taxis
- added Taxis comment
- removed Taxis Locomotion axioms
The comment provides counter example of Taxis without Locomotion, the axioms were further inconsistent as they were (as they were referring to event_types).
> Planning and Taxis

- prolog/uglify.pl
so that the namespace is not the generic 'ns1' in the exported SOMA.owl
> Registering 'soma' as prefix 

- prolog/uglify.pl
to avoid warning about it during swipl process.
> Marking Graph as singleton variable

- owl/SOMA.owl
It turns out, very little needs to change to support linking info objects to entities.
DUL provides an 'is about' property, with inverse 'is reference of'. The 'is about' property has an InformationObject as domain, and ranges over any entity. This can connect the information object to any individual we have more data about.
DUL also provides an 'expresses' property, with inverse 'is expressed by'. The 'expresses' property has InformationObject as domain, and ranges over social objects such as Concepts or Descriptions. This property therefore can be used to link an InformationObject to what it "means".
I added a comment about InformationObjects to describe this intended pattern of usage, such that it is visible when viewing InformationObject in Protege. This pattern of usage is encoded in …
> Added a data property to link DOIs to an InformationObject.

- owl/SOMA.owl
Added three classes: VideoData, MeshShapeData, and KinoDynamicData. The latter two are restricted to only be about physical objects. I was not sure whether to restrict VideoData to events. One could say that a video is about an object too, I guess, though I would not be opposed to have VideoData for events only.
The classes are not declared disjoint, but if you want they could be.
> Added some subclasses of InfoObject

- .github/actions/pythonlatex/Dockerfile
First, thanks for using my little project ([`ChiefGokhlayeh/latex`](https://github.com/ChiefGokhlayeh/latex)) in your CI/CD. I'm quite surprised anyone but myself was actually ever going to use it.
Anyway, I tinkered a bit over the last few days, and switched the `gokhlayeh/latex` image over to Fedora. Fedora uses `dnf` (instead of `apk`) as package manager. Unfortunately this has/will break your [Documentation](https://github.com/ease-crc/soma/actions?query=workflow%3ADocumentation) GitHub Workflow. Note that using `latest` in any CI/CD script is always dangerous.
Here I fixed the image to a specific version, which appears to run smooth, at least in [my fork](https://github.com/ChiefGokhlayeh/soma/actions?query=workflow%3ADocumentation).
> Switch to gokhlayeh/latex:v4

- .github/workflows/deployment.yml
The uploaded ontologies have to be in the build directory.
> Fix deployment workflow for dul

- prolog/uglify.pl
I changed the prefix filtering for imports in the uglify.pl to keep the DUL import
> Modified prefix filter for imports in uglify

- .github/workflows/evaluation.yml
Always when DUL is down the hermit step will not finish. We uploaded DUL ourself so, if we change the path hermit should work again. Additionally I removed IOLite.
I also removed the version of DUL, because I assume that the DUL version in our repository (and therefore on our server), is the current one we use.
> Fix for hermit workflow

- .github/workflows/deployment.yml
- scripts/OntoMetrics.sh
Ontometrics GET interface is not working anymore, therefore I switched to POST. It was necessary to move the metrics step after the "deploying the ontologies" step to have the current OWL file accessible over the URI.
Here is my successful CI run with the new metrics file:
https://github.com/sasjonge/soma/actions/runs/2740607407
Because of the move to POST, I had to add an extra step for a release, so that the metrics are generated from the released version and not the one published as "current".
> Fixed Ontometrics call by moving to a POST call

- scripts/xml2json.py
The new ontometric script creates an xml that contains new lines after each field. Somehow the xml2json script does not work correctly with it. See the broken output here:
https://github.com/ease-crc/soma/blob/1f6fe19f549152d957fdaac6e044a90434750dbe/files/current/metrics.json
`{"Basemetrics": {"Axioms": {"#tail": "\n", "#text": "3797"},
`
should have the form
`{"Basemetrics": {"Axioms": "3797", `
This PR is a simple fix, that will remove the new lines. With this changes we should see the metrics on the website again.
> Minor fix for xml to json converter

- owl/SOMA-ACT.owl
- owl/SOMA-SAY.owl
This PR would resolve https://github.com/ease-crc/soma/issues/213
The last iolite reference creates problems with namespaces in KnowRob (we don't import iolite anymore, so the iolite prefix is not defined, see https://github.com/knowrob/knowrob/blob/808ee2b4a7e4307a1dac17b621845fefefb91fc5/src/model/SOMA.pl#L330), so I would rename the concepts by using the SOMA URI prefix.
> Renamed last iolite URI's

- owl/SOMA-SAY.owl
There was an error in SOMA SAY, probably from #273, where `http://www.ease-crc.org/ont/SOMA.owl#InformationObject` was wrongfully introduced instead of using `http://www.ontologydesignpatterns.org/ont/dul/DUL.owl#InformationObject`.
> Quickfix wrong InformationObject

- scripts/java/application.yaml
At the moment we would have duplicate triples in KnowRob if they appear in SOMA and SOMA-HOME. It also seems to make more sense to me to have SOMA-HOME import SOMA instead of the current merging. 
I wanted to create a SOMA-HOME-bundled file but just adding it to the application.yaml would throw an error.
> Removed SOMA from SOMA-HOME

- owl/SOMA-HOME.owl
I only added a few concepts, including comments.
Some axioms will follow in another pull request.
Not sure though why there is so much refactoring ongoing. I edited with Protege 5.5.0
> Added concepts that were needed to model new IAI apartment.

- owl/SOMA-HOME.owl
- owl/SOMA-OBJ.owl
- owl/SOMA.owl
This pull request adds definitions about that "chairs afford agents that can sit to sit down".
- I also made a rather ad-hoc definition of `Capability` in SOMA-OBJ. apparently Protege also updated a lot in this file, sorry about it, but I don't think it's my fault :P 
- nothing changed in SOMA.owl, only prefixes are apparently handled differently
> First home-domain affordance

- owl/SOMA-ACT.owl
Introduced a more general version of `causes`: `affects` (and its inverse `is affected by`) to express that a variation in the course or outcome of the the subject (the affector) would have resulted in a variation in the object (the affectee), e.g., a planning task that sets parameters such as goal position affects the subsequently executed pick-and-place task that uses that parameter.
This was not captured by `causes`: In the above scenario, the pick-and-place action was not necessarily caused by the planning task, e.g., when otherwise a default value would have been used by the agent.
> Added affects-relationship

- owl/SOMA-AGENT.owl
Builds upons PR https://github.com/ease-crc/soma/pull/297 (Soma-Agent) to add the rest of the preference concepts. Some of the changes from Soma-Agent seem to not directly fit with some concepts of the preference model from the paper:
- currently has the relation `'is quality of' only Agent`
- however, paper proposed `'is preference of' only Agent`
-> should `'is preference of'` be added and used instead? (as a subrelation of `'is quality of'`?)
- Soma-Agent added `Predilection`, but that seems to be slightly different (orders situations instead of discriptions)
-> should `Predilection` be kept as well, or replaced by `Preference Order`?
- Soma-Agent added `Order Item`, which seems to do the same things as far as I can tell
- `Order Item` uses `hasMember` instead of the in the paper …
> Extend preference concepts

- .github/workflows/evaluation.yml
- owl/USD.owl
- scripts/java/src/main/java/main/GuardingXmlCatalogIriMapper.java
- scripts/java/src/main/java/main/OntologyManager.java
- scripts/java/src/main/java/main/ci_runners/OntologySaver.java
USD.owl used the original DUL.owl from ontologydesignpatterns.org, which the CI does not like (this is intentional, since we decided to self-host DUL). This fixes this issue, and also makes it so that the CI will give a better exception when this happens again.
> USD.owl now uses http://www.ease-crc.org/ont/DUL.owl
